// Package config handles loading and saving backup configuration files.
package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Config represents the backup configuration
type Config struct {
	Tag         string
	Paths       []string
	Excludes    []string
	KeepHourly  int
	KeepDaily   int
	KeepWeekly  int
	KeepMonthly int
	KeepYearly  int
	NotifyURL   string
	Schedule    string
}

// DefaultConfig returns a Config with default retention values
func DefaultConfig() *Config {
	return &Config{
		KeepHourly:  0,
		KeepDaily:   7,
		KeepWeekly:  4,
		KeepMonthly: 6,
		KeepYearly:  0,
		Schedule:    "daily",
	}
}

// Load reads the configuration from the specified path
func Load(path string) (*Config, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("failed to open config: %w", err)
	}
	defer file.Close()

	cfg := DefaultConfig()
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")

		switch key {
		case "BACKUP_TAG":
			cfg.Tag = value
		case "BACKUP_PATHS":
			cfg.Paths = strings.Split(value, ",")
		case "BACKUP_EXCLUDES":
			if value != "" {
				cfg.Excludes = strings.Split(value, " ")
			}
		case "KEEP_HOURLY":
			cfg.KeepHourly, _ = strconv.Atoi(value)
		case "KEEP_DAILY":
			cfg.KeepDaily, _ = strconv.Atoi(value)
		case "KEEP_WEEKLY":
			cfg.KeepWeekly, _ = strconv.Atoi(value)
		case "KEEP_MONTHLY":
			cfg.KeepMonthly, _ = strconv.Atoi(value)
		case "KEEP_YEARLY":
			cfg.KeepYearly, _ = strconv.Atoi(value)
		case "NOTIFY_URL":
			cfg.NotifyURL = value
		case "BACKUP_SCHEDULE":
			cfg.Schedule = value
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to read config: %w", err)
	}

	return cfg, nil
}

// Content returns the configuration file content as a string.
func (c *Config) Content() string {
	return fmt.Sprintf(`# Backup configuration generated by bak
# Do not edit manually - use 'bak edit' instead

BACKUP_TAG="%s"
BACKUP_PATHS="%s"
BACKUP_EXCLUDES="%s"
KEEP_HOURLY=%d
KEEP_DAILY=%d
KEEP_WEEKLY=%d
KEEP_MONTHLY=%d
KEEP_YEARLY=%d
NOTIFY_URL="%s"
BACKUP_SCHEDULE="%s"
`,
		c.Tag,
		strings.Join(c.Paths, ","),
		strings.Join(c.Excludes, " "),
		c.KeepHourly,
		c.KeepDaily,
		c.KeepWeekly,
		c.KeepMonthly,
		c.KeepYearly,
		c.NotifyURL,
		c.Schedule,
	)
}

// Save writes the configuration to the specified path
func (c *Config) Save(path string) error {
	return os.WriteFile(path, []byte(c.Content()), 0644)
}

// Exists checks if a configuration file exists at the given path
func Exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// RetentionTag returns the retention tag string for restic
func (c *Config) RetentionTag() string {
	return fmt.Sprintf("retain:h=%d,d=%d,w=%d,m=%d,y=%d",
		c.KeepHourly, c.KeepDaily, c.KeepWeekly, c.KeepMonthly, c.KeepYearly)
}

// WriteCredentials writes the repository credentials to the standard paths.
// It creates the env file and password file with appropriate permissions.
func WriteCredentials(repo, password string) error {
	// Ensure parent directory exists
	configDir := filepath.Dir(DefaultEnvPath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create %s directory: %w", configDir, err)
	}

	// Write password file first (mode 0600 for security)
	if err := os.WriteFile(DefaultPasswordPath, []byte(password+"\n"), 0600); err != nil {
		return fmt.Errorf("failed to write password file: %w", err)
	}

	// Write env file (mode 0644)
	envContent := fmt.Sprintf(`# Restic credentials generated by bak init
RESTIC_REPOSITORY="%s"
RESTIC_PASSWORD_FILE="%s"
RESTIC_CACHE_DIR="%s"
`, repo, DefaultPasswordPath, DefaultCacheDir)

	if err := os.WriteFile(DefaultEnvPath, []byte(envContent), 0644); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}

	return nil
}

// CredentialsExist checks if credential files already exist.
func CredentialsExist() bool {
	return Exists(DefaultEnvPath) || Exists(DefaultPasswordPath)
}

// LoadEnv loads environment variables from the env file
func LoadEnv(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to open env file: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")
		os.Setenv(key, value)
	}

	return scanner.Err()
}
