// Package config handles loading and saving backup configuration files.
package config

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

const (
	// DefaultConfigPath is the default location for the backup configuration
	DefaultConfigPath = "/etc/backup/backup.conf"
	// DefaultEnvPath is the default location for the restic environment file
	DefaultEnvPath = "/etc/backup/env"
)

// Config represents the backup configuration
type Config struct {
	Tag         string
	Paths       []string
	Excludes    []string
	KeepHourly  int
	KeepDaily   int
	KeepWeekly  int
	KeepMonthly int
	KeepYearly  int
	NotifyURL   string
	Schedule    string
}

// DefaultConfig returns a Config with default retention values
func DefaultConfig() *Config {
	return &Config{
		KeepHourly:  0,
		KeepDaily:   7,
		KeepWeekly:  4,
		KeepMonthly: 6,
		KeepYearly:  0,
		Schedule:    "daily",
	}
}

// Load reads the configuration from the specified path
func Load(path string) (*Config, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("failed to open config: %w", err)
	}
	defer file.Close()

	cfg := DefaultConfig()
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")

		switch key {
		case "BACKUP_TAG":
			cfg.Tag = value
		case "BACKUP_PATHS":
			cfg.Paths = strings.Split(value, ",")
		case "BACKUP_EXCLUDES":
			if value != "" {
				cfg.Excludes = strings.Split(value, " ")
			}
		case "KEEP_HOURLY":
			cfg.KeepHourly, _ = strconv.Atoi(value)
		case "KEEP_DAILY":
			cfg.KeepDaily, _ = strconv.Atoi(value)
		case "KEEP_WEEKLY":
			cfg.KeepWeekly, _ = strconv.Atoi(value)
		case "KEEP_MONTHLY":
			cfg.KeepMonthly, _ = strconv.Atoi(value)
		case "KEEP_YEARLY":
			cfg.KeepYearly, _ = strconv.Atoi(value)
		case "NOTIFY_URL":
			cfg.NotifyURL = value
		case "BACKUP_SCHEDULE":
			cfg.Schedule = value
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to read config: %w", err)
	}

	return cfg, nil
}

// Save writes the configuration to the specified path
func (c *Config) Save(path string) error {
	content := fmt.Sprintf(`# Backup configuration generated by bak
# Do not edit manually - use 'bak edit' instead

BACKUP_TAG="%s"
BACKUP_PATHS="%s"
BACKUP_EXCLUDES="%s"
KEEP_HOURLY=%d
KEEP_DAILY=%d
KEEP_WEEKLY=%d
KEEP_MONTHLY=%d
KEEP_YEARLY=%d
NOTIFY_URL="%s"
BACKUP_SCHEDULE="%s"
`,
		c.Tag,
		strings.Join(c.Paths, ","),
		strings.Join(c.Excludes, " "),
		c.KeepHourly,
		c.KeepDaily,
		c.KeepWeekly,
		c.KeepMonthly,
		c.KeepYearly,
		c.NotifyURL,
		c.Schedule,
	)

	return os.WriteFile(path, []byte(content), 0644)
}

// Exists checks if a configuration file exists at the given path
func Exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// RetentionTag returns the retention tag string for restic
func (c *Config) RetentionTag() string {
	return fmt.Sprintf("retain:h=%d,d=%d,w=%d,m=%d,y=%d",
		c.KeepHourly, c.KeepDaily, c.KeepWeekly, c.KeepMonthly, c.KeepYearly)
}

// LoadEnv loads environment variables from the env file
func LoadEnv(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to open env file: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")
		os.Setenv(key, value)
	}

	return scanner.Err()
}
